from __future__ import annotations

from pathlib import Path
from typing import Any

from pecca.connectors.base import Scheduler, register
from pecca.connectors.scheduler.cron import cron_expr
from pecca.core.errors import PeccaError

DAG = '''"""Generated by Pecca. Edit freely."""
from datetime import datetime

from airflow import DAG
from airflow.operators.bash import BashOperator

with DAG("pecca_{name}", schedule="{cron}", start_date=datetime(2026, 1, 1), catchup=False) as dag:
    BashOperator(task_id="{name}", bash_command="{command}")
'''


def PeccaOperator(*args: Any, **kwargs: Any) -> Any:  # noqa: N802
    """Airflow operator that runs one Pecca CLI command. Airflow is imported lazily."""
    try:
        from airflow.operators.bash import BashOperator
    except ImportError as e:
        raise PeccaError("apache-airflow is not installed", "pip install apache-airflow") from e

    class _Op(BashOperator):  # type: ignore[misc]
        def __init__(self, *, pecca_args: list[str], **kw: Any) -> None:
            super().__init__(bash_command="pecca " + " ".join(pecca_args), **kw)

    return _Op(*args, **kwargs)


@register("scheduler", "airflow")
class AirflowScheduler(Scheduler):
    """Writes one DAG file per job into ``dags_dir``."""

    def __init__(self, dags_dir: str = "dags", **_: Any) -> None:
        self.dir = Path(dags_dir)

    def register_job(self, name: str, every: str, command: list[str]) -> None:
        self.dir.mkdir(parents=True, exist_ok=True)
        (self.dir / f"pecca_{name.replace('/', '_')}.py").write_text(
            DAG.format(
                name=name.replace("/", "_"), cron=cron_expr(every), command=" ".join(command)
            )
        )

    def list_jobs(self) -> list[dict[str, Any]]:
        return [
            {"name": p.stem.removeprefix("pecca_"), "file": str(p)}
            for p in sorted(self.dir.glob("pecca_*.py"))
        ]
